# This is a basic workflow to help you get started with Actions

name: CI
env:
  DEPLOYMENT_APPS: '{"mymap": ["app1", "app2", "app3"], "myotherapp": ["app1", "app2", "app4", "app5"]}'


# Controls when the workflow will run
on:
  issue_comment:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  perf_test_request:
    name: Request Perf Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pick assignments or flags
        id: check_regex
        run: |
          while read BODY ; do 
            PR_BODY = $(jq '.comment.body' <<< "$BODY")
            if [[ "$PR_BODY" =~ ^build\ it,\ perf\ it,\ (myotherapp|mymap) ]]; then
              KEY="${BASH_REMATCH[1]}"
              echo "Running Perf for $KEY"
              APPS=$(echo $DEPLOYMENT_APPS | jq -r --arg key "$KEY" '.[$key]|join(","))
              echo "::set-output name=run_build::true"
              echo "::set-output name=deployments::$APPS"
            else
              echo "Regex pattern not matched in PR body."
              echo "::set-output name=run_build::false"
            fi ; done < "$GITHUB_EVENT_PATH"
          
  # This workflow contains a single job called "build"
  build:
    needs: perf_test_request
    if: needs.perf_test_request.outputs.run_build == 'true'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          DEPLOYMENTS="${{ steps.perf_test_request.outputs.deployments }}"
          IFS=","
          for id in $DEPLOYMENTS
          do
            echo "running: $id"
          done
